name: Deploy to Linux Server
on:
  push:
    branches:
      - main # Change this to the branch you want to trigger deployments from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install -qq openssh-client

      - name: Set up SSH agent
        uses: appleboy/ssh-action@master
        with:
          # ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          # key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /usr/local/appSrc/tool-server
            git pull origin main
            service nginx reload
            git status

      # - name: Deploy to Linux server
      #   run: |https://github.com/xuanvien1994/tool-server.git
      #     ssh root@45.77.252.174 "cd /usr/loca/appSrc && git pull origin main"
